/**
 * Exchange API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CurrencyApiModel { 
    id: number;
    name?: string;
    code?: string;
    minDepositAmount: number;
    minWithdrawAmount: number;
    maxDepositAmount: number;
    maxWithdrawAmount: number;
    dailyMaxDepositAmount: number;
    dailyMaxWithdrawAmount: number;
}
