/**
 * Exchange API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type OrderStatus = 1 | 2 | 3 | 4 | 5;

export const OrderStatus = {
    NUMBER_1: 1 as OrderStatus,
    NUMBER_2: 2 as OrderStatus,
    NUMBER_3: 3 as OrderStatus,
    NUMBER_4: 4 as OrderStatus,
    NUMBER_5: 5 as OrderStatus
};
