/**
 * Exchange API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type OrderType = 1 | 2 | 3 | 4;

export const OrderType = {
    NUMBER_1: 1 as OrderType,
    NUMBER_2: 2 as OrderType,
    NUMBER_3: 3 as OrderType,
    NUMBER_4: 4 as OrderType
};
