/**
 * Exchange API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrderCondition } from './orderCondition';
import { OrderType } from './orderType';


export interface OrderRequestModel { 
    marketId: number;
    rate: number;
    stopRate?: number;
    quantity: number;
    isBuy: boolean;
    orderType: OrderType;
    orderCondition: OrderCondition;
    isIcebergOrger: boolean;
    icebergQuantity?: number;
    cancelOn: Date;
}
