/**
 * Exchange API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type OrderCondition = 0 | 1 | 2 | 4;

export const OrderCondition = {
    NUMBER_0: 0 as OrderCondition,
    NUMBER_1: 1 as OrderCondition,
    NUMBER_2: 2 as OrderCondition,
    NUMBER_4: 4 as OrderCondition
};
