/**
 * Exchange API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrderCondition } from './orderCondition';
import { OrderStatus } from './orderStatus';
import { OrderType } from './orderType';


export interface OrderResponseModel { 
    id: number;
    quantity: number;
    rate: number;
    stopRate: number;
    isBuy: boolean;
    quantityRemaining: number;
    marketId: number;
    createdOn: Date;
    quantityExecuted: number;
    lockedBalance: number;
    fee: number;
    feeCurrencyId: number;
    tradeFeeId: number;
    cancelOn?: Date;
    icebergQuantity?: number;
    orderType: OrderType;
    orderStatus: OrderStatus;
    orderCondition: OrderCondition;
}
